# Generated by Django 6.1.1 on 2026-09-05 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('space', models.IntegerField(db_column='hospi', help_text='Número del hospi', verbose_name='número de hospi')),
                ('dedicated', models.CharField(choices=[('GAT', 'cat'), ('PER', 'dog')], db_column='type_of_animal', help_text='Código corto del animal (GAT o PER)', max_length=3, verbose_name='tipo de animal')),
            ],
            options={
                'verbose_name_plural': 'Availabilities',
                'db_table': 'availability',
            },
        ),
        migrations.CreateModel(
            name='Occupant',
            fields=[
                ('occupant_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name_occupant', help_text='Nombre del animal', max_length=25, verbose_name='nombre')),
                ('weight', models.FloatField(blank=True, db_column='weight_animal', help_text='Peso del animal', null=True, verbose_name='peso')),
                ('motive', models.CharField(blank=True, db_column='motive', help_text='Motivo de consulta', max_length=127, null=True, verbose_name='motivo de consulta')),
                ('correa', models.CharField(blank=True, db_column='correa_description', help_text='Descripción correa', max_length=31, null=True, verbose_name='correa')),
                ('transportin', models.CharField(blank=True, db_column='transportin_description', help_text='Descripción transportín', max_length=31, null=True, verbose_name='transportín')),
                ('attention', models.TextField(blank=True, db_column='attention', help_text='Notas de atención', null=True, verbose_name='atención')),
                ('space', models.OneToOneField(db_column='space_occupant', error_messages={'unique': 'Este espacio ya está ocupado.'}, on_delete=django.db.models.deletion.CASCADE, related_name='occupant', to='hospi_mgmt.availability', verbose_name='espacio')),
            ],
        ),
    ]
