# Generated by Django 6.0.2 on 2026-02-13 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space', models.IntegerField(db_column='hospi', help_text='Number of the hospi', verbose_name='hospi number')),
                ('dedicated', models.CharField(choices=[('GAT', 'cat'), ('PER', 'dog')], db_column='type_of_animal', help_text='Short code of animal (GAT or PER)', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Availabilities',
            },
        ),
        migrations.CreateModel(
            name='Occupant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name_occupant', help_text='Nombre del animal', max_length=25, verbose_name='occupant')),
                ('weight', models.FloatField(blank=True, db_column='weight_animal', help_text='Peso del animal', null=True)),
                ('motive', models.CharField(blank=True, db_column='motive', help_text='Motivo de consulta', max_length=127, null=True)),
                ('correa', models.CharField(blank=True, db_column='correa_description', help_text='Descripción correa', max_length=31, null=True)),
                ('transportin', models.CharField(blank=True, db_column='transportin_description', help_text='Descripción transportín', max_length=31, null=True)),
                ('attention', models.TextField(blank=True, db_column='attention', help_text='Attention', null=True)),
                ('space', models.OneToOneField(db_column='space_occupant', error_messages={'unique': 'Este espacio ya está ocupado.'}, help_text='Eliga un espacio', on_delete=django.db.models.deletion.CASCADE, related_name='occupant', to='hospi_mgmt.availability')),
            ],
        ),
    ]
